---
apiVersion: v1
kind: 	Secret
metadata: 
  name: {{ .secretvalues.name_1 }}
data: {{  .secretvalues.data_booksdb | toYaml | nindent 4 }}
   
---
apiVersion: v1
kind: 	Secret
metadata: 
  name: {{ .secretvalues.name_2 }}
data: {{  .secretvalues.data_userdb | toYaml | nindent 4 }}
    
---
apiVersion: v1
kind: 	Secret
metadata: 
  name: {{ .secretvalues.name_3 }}
data: {{  .secretvalues.data_books_svc | toYaml | nindent 4 }}
    
---
apiVersion: v1
kind: 	Secret
metadata: 
  name: {{ .secretvalues.name_4 }}
data: {{  .secretvalues.data_user_svc | toYaml | nindent 4 }}
---
apiVersion: v1
kind: 	Secret
metadata: 
  name: {{ .secretvalues.name_5 }}
data:  {{  .secretvalues.data_lib_webstore | toYaml | nindent 4 }}




