---
apiVersion: v1
kind: Service
metadata: 
  name: spc-svc
  labels: 
    app: svc
spec:
  type: NodePort
  selector:
    app: svc
  ports:
   - port: 8080
     targetport: 8080
     protocol: TCP

    




