---
name: user-db
namespace: 
  app: user-db
spec:
  minReadySeconds: 5
  replicas: 1
image: postgres:15-alpine
secretRef: 
  name : secret-user-db
resources:
  limits:
    cpu: 500m
    memory: 128M
  requests:
    cpu: 100m
    memory: 24M
ports:
  - containerPort: 5432
spec-svc: 
  type: ClusterIP
ports-svc: 
  - port: 5432
    targetPort: 5432