apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate: 
    metadata:
      labels: 
        app: cronjob-lb
    spec:
      template: 
        metadata:
          labels: 
            app: cronjob-lb
        spec:
          containers:
            - name: cronjob-container
              image: alpine:3.18
              args:
                - sleep
                - 30s
          restartPolicy: OnFailure