---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
  annotations: 
    kubernetes.io/change-cause: "version v1.0"
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    matchLabels: 
      name: deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: deployment 
      labels: 
        name: deployment
    spec:
      containers: 
       -  name: dep-con
          image: shaikkhajaibrahim/dmtest  
          resources:
            requests:
              memory: 24Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 200m
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: dep-svc
spec:
  ports:
   -  port: 80
      targetPort: 80
  selector: 
    name: deployment
  type: NodePort






              

        

    

