apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: books-svc
  labels: 
    app: books-svc
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-svc
  template: 
    metadata:
      labels:
        app: books-svc
    spec:
      containers:
        -   name: books-svc
            image: shaikkhajaibrahim/libbookssvc:1.0
            envFrom:
              - configMapRef: 
                  name: configmap-books-svc
            resources:
              limits:
                cpu: 500m
                memory: 128M
              requests:
                cpu: 100m
                memory: 24M
            ports:
              - containerPort: 8000 

---
apiVersion: v1
kind: Service
metadata: 
  name: books-svc
spec:
  type: ClusterIP
  selector:
    app: books-svc
  ports:
    - port: 8000
      targetPort: 8000