apiVersion: apps/v1
kind: Deployment
metadata: 
  name: books-svc
  labels: 
    app: books-svc
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-svc
  template: 
    metadata:
      labels:
        app: books-svc
    spec:
      automountServiceAccountToken: false
      containers:
        - name: books-service
          image: shaikkhajaibrahim/libbookssvc:1.0
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          envFrom:
            - secretRef:
                name: secret-books-svc
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: books-svc
spec:
  type: ClusterIP
  selector:
    app: books-svc
  ports:
    - port: 8000
      targetPort: 8000