apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: books-db
  labels: 
    app: books-db
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-db
  template: 
    metadata:
      labels:
        app: books-db
    spec:
      containers:
        -   name: booksdb
            image: postgres:15-alpine
            envFrom:
            -  configMapRef: 
                name: configmap-books-db
            resources:
              limits:
                cpu: 500m
                memory: 128M
              requests:
                cpu: 100m
                memory: 24M
            ports:
              - containerPort: 5432   

---
apiVersion: v1
kind: Service
metadata: 
  name: books-db
spec:
  type: ClusterIP
  selector:
    app: books-db
  ports:
    - port: 5432
      targetPort: 5432