---
apiVersion: v1
kind: 	ConfigMap
metadata: 
  name: configmap-books-db
data: 
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: booksdb
---
apiVersion: v1
kind: 	ConfigMap
metadata: 
  name: configmap-user-db
data: 
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: userdb
---
apiVersion: v1
kind: 	ConfigMap
metadata: 
  name: configmap-books-svc
data: 
    DATABASE_URL: "postgresql://user:password@books-db:5432/booksdb"
    SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
---
apiVersion: v1
kind: 	ConfigMap
metadata: 
  name: configmap-users-svc
data: 
    DATABASE_URL: "postgresql://user:password@user-db:5432/userdb"
    SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
---
apiVersion: v1
kind: 	ConfigMap
metadata: 
  name: configmap-lib-webstore
data: 
    REACT_APP_BACKEND_API_URL: http://user-svc:8000/api/v1
    REACT_APP_BOOKS_API_URL: http://books-svc:8000/api/v1/books
    REACT_APP_USERS_API_URL: http://user-svc:8000/api/v1/users



