apiVersion: apps/v1
kind: Deployment
metadata: 
  name: lib-web
  labels: 
    app: lib-web
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: lib-web
  template: 
    metadata:
      labels:
        app: lib-web
    spec:
      containers:
        -   name: lib-web
            image: shaikkhajaibrahim/libwebstore:1.0
            envFrom:
              - secretRef: 
                 name: secret-lib-webstore
            resources:
              limits:
                cpu: 500m
                memory: 128M
              requests:
                cpu: 100m
                memory: 24M
            ports:
              - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata: 
  name: lib-web-svc
spec:
  type: LoadBalancer
  selector:
    app: lib-web
  ports:
    - port: 80
      targetPort: 3000