apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: user-svc
  labels: 
    app: user-svc
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: user-svc
  template: 
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
        - name: users-service
          image: shaikkhajaibrahim/libuserssvc:1.0
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          envFrom:
            # - configMapRef:
            #     name: users-svc-config
            - secretRef:
                name: secret-users-svc
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: user-svc
spec:
  type: ClusterIP
  selector:
    app: user-svc
  ports:
    - port: 8000
      targetPort: 8000