apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: user-svc
  labels: 
    app: user-svc
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: user-svc
  template: 
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
        -   name: user-svc
            image: shaikkhajaibrahim/libuserssvc:1.0
            env:
              - name: DATABASE_URL
                value: "postgresql://user:password@user-db:5432/userdb"
              - name: SECRET_KEY
                value: YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k
            resources:
              limits:
                cpu: 500m
                memory: 128M
              requests:
                cpu: 100m
                memory: 24M
            ports:
              - containerPort: 8000 

---
apiVersion: v1
kind: Service
metadata: 
  name: user-svc
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 8000
      targetPort: 8000