---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ .Values.namespace }}
  labels: {{ .Values.lables| toYaml | nindent 2}}
spec: {{ .Values.spec | toYaml | nindent 4}}
  selector:
    matchLabels: {{ .Values.lables| toYaml | nindent 6}}
  template:
    metadata:  {{ .Values.lables| toYaml | nindent 8}} 
    spec:
      containers:
      - name: {{ .Values.namespace }} app-svc
        image: {{ .Values.image }}
      resources: {{ .Values.res | toYaml | nindent 8 }}
      ports:
        - containerPort: {{ .Values.chart }}
          protocol: {{ .Values.protocol }}
        args: {{ .Values.val| toYaml | nindent 8}}
