---
namespace: replicaset1
chart: 8080
lables:
  app: svc
spec: 
  minReadySeconds: 3
  replicas: 1
val:
  - sleep
  - 10s
res:
   requests: 
     cpu: 100m
     memory: 128mi
   limits:
     cpu: 500m
     memory: 300mi
image: shaikkhajaibrahim/spcjan2024:1.0
protocol: TCP